// Run with PLAYWRIGHT_MODULE set to the installed playwright/index.mjs if needed.
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve, extname, sep } from 'node:path';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = resolve('web');
const server = createServer(async (req, res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
    const file = resolve(root, '.' + pathname + (pathname.endsWith('/') ? 'index.html' : ''));
    if (!file.startsWith(root + sep)) { res.writeHead(403).end(); return; }
    const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.png': 'image/png', '.webmanifest': 'application/manifest+json' };
    res.writeHead(200, { 'Content-Type': types[extname(file)] || 'text/plain', 'Cache-Control': 'no-store' }); res.end(await readFile(file));
  } catch { res.writeHead(404).end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const url = process.env.PROTOTYPE_URL || `http://localhost:${server.address().port}/passkeys/`;
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXE ? { executablePath: process.env.BROWSER_EXE } : {}) });
let context;
try {
  context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const cdp = await context.newCDPSession(page); await cdp.send('WebAuthn.enable');
  const { authenticatorId } = await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  await page.goto(url);
  await page.clock.install();
  await page.locator('#start').click();
  await page.locator('#enroll').click();
  await page.locator('#activation-message').filter({ hasText: 'Appuyez d’abord' }).waitFor();
  await page.locator('#approve').click();
  const firstPassword = await page.locator('#demo-password').textContent();
  await page.locator('#enroll').click();
  assert.equal((await cdp.send('WebAuthn.getCredentials', { authenticatorId })).credentials.length, 0);
  await page.locator('#username').fill('wrong-user'); await page.locator('#password').fill(firstPassword);
  await page.locator('#enroll').click();
  await page.locator('#activation-message.error').filter({ hasText: 'Identifiant ou mot de passe incorrect' }).waitFor();
  assert.ok(await page.locator('#activation-message').evaluate(el => { const box = el.getBoundingClientRect(); return box.top >= 0 && box.bottom <= innerHeight; }));
  await page.locator('#username').fill('stock.test'); await page.locator('#password').fill('wrong-password');
  for (let attempt = 0; attempt < 4; attempt++) await page.locator('#enroll').click();
  await page.locator('#password').fill(firstPassword); await page.locator('#enroll').click();
  await page.locator('#activation-message.error').filter({ hasText: 'Cinq essais incorrects' }).waitFor();
  assert.equal((await cdp.send('WebAuthn.getCredentials', { authenticatorId })).credentials.length, 0);
  await page.locator('#back').click(); await page.goBack();
  assert.equal(await page.locator('#username').inputValue(), '');
  assert.equal(await page.locator('#password').inputValue(), '');
  assert.equal(await page.locator('#enroll').isDisabled(), false);
  await page.goForward();
  await page.locator('#start').click(); await page.locator('#approve').click();
  await page.locator('#username').fill('stock.test'); await page.locator('#password').fill(await page.locator('#demo-password').textContent());
  await page.clock.fastForward(600001);
  await page.locator('#enroll').click();
  await page.locator('#activation-message.error').filter({ hasText: 'expirés' }).waitFor();
  await page.locator('#back').click();
  await page.locator('#start').click(); await page.locator('#approve').click();
  const password = await page.locator('#demo-password').textContent();
  await page.locator('#username').fill(await page.locator('#demo-username').textContent());
  await page.locator('#password').fill(password); await page.locator('#show-password').click();
  assert.equal(await page.locator('#password').getAttribute('type'), 'text');
  await page.locator('#show-password').click();
  assert.equal(await page.locator('#password').getAttribute('type'), 'password');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.locator('#password').fill('');
  await page.screenshot({ path: 'tests/passkeys/mobile-activation.png', fullPage: true });
  await page.locator('#password').fill(password); await page.locator('#enroll').click();
  await page.locator('[data-screen="create"]:visible').waitFor();
  assert.equal((await cdp.send('WebAuthn.getCredentials', { authenticatorId })).credentials.length, 0);
  // Registration remains gated by a separate, native click (including retry after cancellation).
  await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId, enabled: false });
  await page.locator('#create-passkey').click(); await page.locator('#cancel-passkey').click();
  assert.equal(await page.locator('#create-passkey').isDisabled(), false);
  assert.equal((await cdp.send('WebAuthn.getCredentials', { authenticatorId })).credentials.length, 0);
  await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId, enabled: true });
  await page.locator('#create-passkey').click();
  await page.locator('[data-screen="ready"]:visible').waitFor();
  assert.equal(await page.locator('#password').inputValue(), '');
  assert.equal(await page.locator('#username').inputValue(), '');
  assert.equal(await page.locator('#demo-password').textContent(), '');
  assert.equal(await page.locator('#enroll').isDisabled(), false);
  assert.equal(await page.evaluate(secret => JSON.stringify(localStorage).includes(secret) || JSON.stringify(history.state).includes(secret), password), false);
  await page.locator('#first-login').click(); await page.locator('[data-screen="session"]:visible').waitFor();
  await page.locator('#check-session').click(); assert.match(await page.locator('#message').textContent(), /encore valide/);
  await page.reload(); await page.locator('[data-screen="session"]:visible').waitFor();
  await page.locator('#logout').click(); await page.locator('#login').click(); await page.locator('[data-screen="session"]:visible').waitFor();
  await page.locator('[data-screen="session"] [data-go="transfer"]').click(); await page.locator('#make-transfer').click();
  const transfer = await page.locator('#export-link').inputValue();
  const publicProfile = await page.evaluate(() => JSON.parse(localStorage.getItem('stock.passkey-prototype.v1')).profile);
  assert.ok(!transfer.includes('privateKey')); assert.ok(publicProfile.publicKey);
  // New browser storage; synthetic authenticator credential transferred only inside the test harness.
  const { credentials } = await cdp.send('WebAuthn.getCredentials', { authenticatorId });
  const context2 = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page2 = await context2.newPage(); page2.on('pageerror', e => errors.push(e.message));
  const cdp2 = await context2.newCDPSession(page2); await cdp2.send('WebAuthn.enable');
  const { authenticatorId: id2 } = await cdp2.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  await cdp2.send('WebAuthn.addCredential', { authenticatorId: id2, credential: credentials[0] });
  await page2.goto(transfer); assert.equal(new URL(page2.url()).hash, '#transfer');
  await page2.locator('#import-profile').click(); await page2.locator('#message').filter({ hasText: 'Fiche publique chargée' }).waitFor();
  await page2.locator('#transfer-login').click(); await page2.locator('[data-screen="session"]:visible').waitFor();
  await page2.locator('[data-screen="session"] summary').click(); await page2.locator('#revoke').click(); await page2.locator('#login').click();
  await page2.locator('#message.error').filter({ hasText: 'révoqué' }).waitFor();
  // Revocation did not silently alter the first storage (explicit limitation of the demo).
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('stock.passkey-prototype.v1')).revoked), false);
  await page2.goBack(); assert.equal(await page2.locator('[data-screen="session"]:visible').count(), 0);
  await context2.close();
  // Restoring a pending request must not create a session after navigation.
  await page.locator('#back').click(); await page.locator('#login').click(); await page.locator('#logout').click();
  await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId, enabled: false });
  await page.locator('#login').click(); await page.locator('[data-go="diagnostic"]').click();
  await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId, enabled: true });
  assert.equal(await page.evaluate(() => sessionStorage.getItem('stock.passkey-prototype.session.v1')), null);
  assert.equal(await page.locator('[data-screen="diagnostic"]:visible').count(), 1);
  await page.locator('#back').click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'tests/passkeys/mobile-home.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: 'tests/passkeys/desktop-home.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('Browser PASS: temporary username/password, invalid credentials, expiry, lockout, credential clearing, visible mobile errors, native-click registration, cancellation/retry, activation, real virtual WebAuthn create/get, signature verification, session reload/logout, public transfer to isolated storage, local revocation, back navigation, pending-operation cancellation, mobile layout.');
} finally { await context?.close(); await browser.close(); await new Promise(resolve => server.close(resolve)); }
